### PR TITLE
feat: add quick pick to open a loaded script

### PR DESCRIPTION
**Pull request by connor4312**
For https://github.com/microsoft/vscode/issues/85950. Works just like the v1 adapter!

### CODE REVIEW

**Comment by connor4312** [comment]
It's less useful now that tree views can be filtered. This is a parity item with the v1 adapter, though it doesn't look like the v1 command is used very often.

**Comment by roblourens** [comment]
I forgot we have this in v1, I don't think I've ever used it

**Comment by weinand** [comment]
The plan was to remove the quickpick as soon as we get tree filtering.

**Comment by connor4312** [comment]
Ok, I'll close this then, thanks for confirming!

**Pull request closed without merging**
